language: generic 

sudo: required
services:
  - docker

before_install:
  - docker build -t lilbig/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true lilbig/docker-react npm run test -- --coverage